// GENERATED FILE - DO NOT EDIT.
// ignore_for_file: type=lint, unused_import, camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// Dart FFI bindings for the tacit_llama C-API (llama.cpp bridge).
class TacitLlamaBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  TacitLlamaBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  TacitLlamaBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void tacit_free_backend() {
    return _tacit_free_backend();
  }

  late final _tacit_free_backendPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('tacit_free_backend');
  late final _tacit_free_backend = _tacit_free_backendPtr
      .asFunction<void Function()>();

  void tacit_free_string(ffi.Pointer<ffi.Char> s) {
    return _tacit_free_string(s);
  }

  late final _tacit_free_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'tacit_free_string',
      );
  late final _tacit_free_string = _tacit_free_stringPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> tacit_generate(
    ffi.Pointer<tacit_model> model,
    ffi.Pointer<ffi.Char> prompt,
    int max_tokens,
    double temperature,
  ) {
    return _tacit_generate(model, prompt, max_tokens, temperature);
  }

  late final _tacit_generatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<tacit_model>,
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
            ffi.Float,
          )
        >
      >('tacit_generate');
  late final _tacit_generate = _tacit_generatePtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<tacit_model>,
          ffi.Pointer<ffi.Char>,
          int,
          double,
        )
      >();

  int tacit_generate_stream(
    ffi.Pointer<tacit_model> model,
    ffi.Pointer<ffi.Char> prompt,
    int max_tokens,
    double temperature,
    tacit_piece_cb cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _tacit_generate_stream(
      model,
      prompt,
      max_tokens,
      temperature,
      cb,
      user_data,
    );
  }

  late final _tacit_generate_streamPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<tacit_model>,
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
            ffi.Float,
            tacit_piece_cb,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('tacit_generate_stream');
  late final _tacit_generate_stream = _tacit_generate_streamPtr
      .asFunction<
        int Function(
          ffi.Pointer<tacit_model>,
          ffi.Pointer<ffi.Char>,
          int,
          double,
          tacit_piece_cb,
          ffi.Pointer<ffi.Void>,
        )
      >();

  bool tacit_init_backend() {
    return _tacit_init_backend();
  }

  late final _tacit_init_backendPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>('tacit_init_backend');
  late final _tacit_init_backend = _tacit_init_backendPtr
      .asFunction<bool Function()>();

  ffi.Pointer<ffi.Char> tacit_last_error() {
    return _tacit_last_error();
  }

  late final _tacit_last_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'tacit_last_error',
      );
  late final _tacit_last_error = _tacit_last_errorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  void tacit_model_free(ffi.Pointer<tacit_model> model) {
    return _tacit_model_free(model);
  }

  late final _tacit_model_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<tacit_model>)>>(
        'tacit_model_free',
      );
  late final _tacit_model_free = _tacit_model_freePtr
      .asFunction<void Function(ffi.Pointer<tacit_model>)>();

  ffi.Pointer<tacit_model> tacit_model_load(ffi.Pointer<ffi.Char> model_path) {
    return _tacit_model_load(model_path);
  }

  late final _tacit_model_loadPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<tacit_model> Function(ffi.Pointer<ffi.Char>)
        >
      >('tacit_model_load');
  late final _tacit_model_load = _tacit_model_loadPtr
      .asFunction<ffi.Pointer<tacit_model> Function(ffi.Pointer<ffi.Char>)>();

  int tacit_reset(ffi.Pointer<tacit_model> model) {
    return _tacit_reset(model);
  }

  late final _tacit_resetPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<tacit_model>)>>(
        'tacit_reset',
      );
  late final _tacit_reset = _tacit_resetPtr
      .asFunction<int Function(ffi.Pointer<tacit_model>)>();
}

final class tacit_model extends ffi.Opaque {}

typedef tacit_piece_cb =
    ffi.Pointer<ffi.NativeFunction<tacit_piece_cbFunction>>;
typedef tacit_piece_cbFunction = ffi.Int Function(
  ffi.Pointer<ffi.Char> piece,
  ffi.Pointer<ffi.Void> user_data,
);
typedef Darttacit_piece_cbFunction = int Function(
  ffi.Pointer<ffi.Char> piece,
  ffi.Pointer<ffi.Void> user_data,
);
