// GENERATED FILE - DO NOT EDIT.
// ignore_for_file: type=lint, unused_import, camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// Dart FFI bindings for the tacit_whisper C-API (whisper.cpp bridge).
class TacitWhisperBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  TacitWhisperBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  TacitWhisperBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Releases the model context. NULL is fine.
  void tacit_whisper_free(ffi.Pointer<tacit_whisper_context> ctx) {
    return _tacit_whisper_free(ctx);
  }

  late final _tacit_whisper_freePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<tacit_whisper_context>)
        >
      >('tacit_whisper_free');
  late final _tacit_whisper_free = _tacit_whisper_freePtr
      .asFunction<void Function(ffi.Pointer<tacit_whisper_context>)>();

  /// Segment start offset in whisper.cpp time units (10 ms ticks), matching the
  /// upstream whisper_full_get_segment_t0 semantics.
  int tacit_whisper_full_get_segment_t0(
    ffi.Pointer<tacit_whisper_context> ctx,
    int i_segment,
  ) {
    return _tacit_whisper_full_get_segment_t0(ctx, i_segment);
  }

  late final _tacit_whisper_full_get_segment_t0Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int64 Function(ffi.Pointer<tacit_whisper_context>, ffi.Int)
        >
      >('tacit_whisper_full_get_segment_t0');
  late final _tacit_whisper_full_get_segment_t0 =
      _tacit_whisper_full_get_segment_t0Ptr
          .asFunction<int Function(ffi.Pointer<tacit_whisper_context>, int)>();

  /// Segment end offset in whisper.cpp time units (10 ms ticks).
  int tacit_whisper_full_get_segment_t1(
    ffi.Pointer<tacit_whisper_context> ctx,
    int i_segment,
  ) {
    return _tacit_whisper_full_get_segment_t1(ctx, i_segment);
  }

  late final _tacit_whisper_full_get_segment_t1Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int64 Function(ffi.Pointer<tacit_whisper_context>, ffi.Int)
        >
      >('tacit_whisper_full_get_segment_t1');
  late final _tacit_whisper_full_get_segment_t1 =
      _tacit_whisper_full_get_segment_t1Ptr
          .asFunction<int Function(ffi.Pointer<tacit_whisper_context>, int)>();

  /// Segment text pointer owned by the native context; valid until the next
  /// tacit_whisper_transcribe call on the same handle. Returns NULL on error.
  ffi.Pointer<ffi.Char> tacit_whisper_full_get_segment_text(
    ffi.Pointer<tacit_whisper_context> ctx,
    int i_segment,
  ) {
    return _tacit_whisper_full_get_segment_text(ctx, i_segment);
  }

  late final _tacit_whisper_full_get_segment_textPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<tacit_whisper_context>,
            ffi.Int,
          )
        >
      >('tacit_whisper_full_get_segment_text');
  late final _tacit_whisper_full_get_segment_text =
      _tacit_whisper_full_get_segment_textPtr
          .asFunction<
            ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<tacit_whisper_context>,
              int,
            )
          >();

  /// Number of segments produced by the last successful tacit_whisper_transcribe
  /// call, or 0 when there is no context / no result yet.
  int tacit_whisper_full_n_segments(ffi.Pointer<tacit_whisper_context> ctx) {
    return _tacit_whisper_full_n_segments(ctx);
  }

  late final _tacit_whisper_full_n_segmentsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<tacit_whisper_context>)>
      >('tacit_whisper_full_n_segments');
  late final _tacit_whisper_full_n_segments = _tacit_whisper_full_n_segmentsPtr
      .asFunction<int Function(ffi.Pointer<tacit_whisper_context>)>();

  /// Loads a whisper.cpp model (e.g. ggml-base.bin) from a filesystem path.
  /// Returns a handle, or NULL on failure (query tacit_whisper_last_error).
  /// The caller must release it with tacit_whisper_free().
  ffi.Pointer<tacit_whisper_context> tacit_whisper_init(
    ffi.Pointer<ffi.Char> model_path,
  ) {
    return _tacit_whisper_init(model_path);
  }

  late final _tacit_whisper_initPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<tacit_whisper_context> Function(ffi.Pointer<ffi.Char>)
        >
      >('tacit_whisper_init');
  late final _tacit_whisper_init = _tacit_whisper_initPtr
      .asFunction<
        ffi.Pointer<tacit_whisper_context> Function(ffi.Pointer<ffi.Char>)
      >();

  /// Human-readable description of the last error on this thread, or NULL.
  ffi.Pointer<ffi.Char> tacit_whisper_last_error() {
    return _tacit_whisper_last_error();
  }

  late final _tacit_whisper_last_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'tacit_whisper_last_error',
      );
  late final _tacit_whisper_last_error = _tacit_whisper_last_errorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Runs one synchronous full transcription over a 16 kHz mono Float32 PCM
  /// buffer. `language` is an ISO-639 code ("id", "en", ...); pass NULL or an
  /// empty string to let whisper.cpp auto-detect the spoken language (the Dart
  /// bridge defaults to "id" for technician voice notes).
  /// Returns 0 on success, non-zero on failure (query tacit_whisper_last_error).
  /// Thread-safety: serialized per handle; safe while another handle runs.
  int tacit_whisper_transcribe(
    ffi.Pointer<tacit_whisper_context> ctx,
    ffi.Pointer<ffi.Float> pcm_data,
    int n_samples,
    ffi.Pointer<ffi.Char> language,
  ) {
    return _tacit_whisper_transcribe(ctx, pcm_data, n_samples, language);
  }

  late final _tacit_whisper_transcribePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<tacit_whisper_context>,
            ffi.Pointer<ffi.Float>,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('tacit_whisper_transcribe');
  late final _tacit_whisper_transcribe = _tacit_whisper_transcribePtr
      .asFunction<
        int Function(
          ffi.Pointer<tacit_whisper_context>,
          ffi.Pointer<ffi.Float>,
          int,
          ffi.Pointer<ffi.Char>,
        )
      >();
}

final class tacit_whisper_context extends ffi.Opaque {}
